In [ ]:
# 1. *What is pandas* - An open-source Python package that is most widely used for data science/data analysis and machine learning tasks.

# 2. What are the 2 collections used in Pandas? - Series and Dataframe series.

# 3. Name 4 things Pandas can do for us - Load Data, Clean Data, Manipulate and analyze data.

# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?  Inplace

# 5. What is a csv? *a text file format that uses commas to separate values and organizes it into table format*

# 6. When cleaning data what values do we not like in our data? Nulls

In [46]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np

aArray = np.array([[8,17], [9,3],[89,90]])
print(aArray)
newshape = aArray.reshape(2,-1)
print(newshape) #why can I choose any negatve for the second number but not positives?

[[ 8 17]
 [ 9  3]
 [89 90]]
[[ 8 17  9]
 [ 3 89 90]]


In [50]:
# 8. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

arrayb = np.linspace(0,20, num = 6)
print(arrayb)

[ 0.  4.  8. 12. 16. 20.]


In [51]:
# 9. Make a Deep Copy of the above array

import copy

arrayb = ((0,4,8,12,16,20))
arrayc = copy.deepcopy(arrayb)
print(arrayc)


(0, 4, 8, 12, 16, 20)


In [4]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...

import numpy as np

oldarray1 = ([[25, 16]])
oldarray2 = ([[11, 2], [13, 4]])
oldarray3 = ([[7, 81], [5, 6], [11, 12]])

newarray = np.concatenate((oldarray1,oldarray2,oldarray3),axis =0)
print(newarray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [6]:
# 11. Sort 'newArray' in order into 'sortedArray'

import numpy as np

sortedarray = np.sort(newarray)
print(sortedarray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [9]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

import numpy as np


a,b,c,d,e,f = newarray

print(a)
print(b)
print(c)
print(d)
print(e)
print(f) 

# I made the correction but i dont know why im getting an error.


NameError: name 'newarray' is not defined

In [13]:
#13. Combined and sort the following arrays into one called 'comboArray' ...


one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)
print(comboArray)

comboArray = np.sort(comboArray)
print(comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [28]:
# 14. Take 'comboArray' and perform the following slicing activities:

import numpy as np

print(comboArray[1])
print(comboArray[2:24])
print(comboArray[3:15])
print(comboArray[18:24])
print(comboArray[-24:-10])
print(comboArray[16::2])
print(comboArray[23::-5]) #unsure on this one, do I somehow loop this array??

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [35]:
# 15. Using Series, create a DataFrame that looks like this:

import pandas as pd

ingredients = pd.Series (["flour","milk","eggs","spam"])
quantity = pd.Series ([4,1,2,1])
unit = pd.Series (["cups","cup","large","can"])

print(ingredients)
print(quantity)
print(unit)




0    flour
1     milk
2     eggs
3     spam
dtype: object
0    4
1    1
2    2
3    1
dtype: int64
0     cups
1      cup
2    large
3      can
dtype: object


In [51]:
import pandas as pd

# 16. Take this data and create a DataFrame named studentData

studentdata = {"Name": ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        "Height": [5.1, 6.2, 5.1, 5.2],
        "Qualification": ['Msc', 'MA', 'Msc', 'Msc'],
        "address": ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
         "Age": [21, 23, 24, 21],
         "Pets": ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
          "sport": ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}
        
studentData = pd.DataFrame(studentdata)

# 17.Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentdata['desserts'] = desserts

# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name", "address"], inplace = True)
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball


In [52]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

df = pd.read_csv('cows_and_goats.csv')
print(df)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [53]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

df = pd.DataFrame({'broccoli': [12, 20], 'peppers': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('vegetables.csv')
